### ISSUE TITLE
MS6 Checklist

### ISSUE THREAD

**Issue by parnellj15** [SP19MIS4173T11/Team11#3]
- [x] Update and move Milestone 1 deliverable's into Milestone 6 report.

- [x] Update and move Milestone 2 deliverable's into Milestone 6 report.

- [x] Update and move Milestone 3 deliverable's into Milestone 6 report.

- [x] Update and move Milestone 4 deliverable's into Milestone 6 report.

- [x] Create new mock-up and sample data.

- [x] Program code for each program.

- [x] Explanation of challenges, problems, and discoveries.

- [x] Update and move Milestone 5 deliverable's into Milestone 6 report.

- [x] Team member project assessments.

- [x] Complete and attach Project Plan.

- [x] Update Time sheets

- [x] Submit Milestone 6 deliverable's.
